create table if not exists holidays (
  id bigint generated by default as identity primary key,
  date date not null unique,
  holiday_name text not null,
  year integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists holidays_year_idx on holidays (year);
